/**
 * Sentinel Gl -- an OpenGL based remake of the Firebird classic the Sentinel.
 * Copyright (C) May 25th, 2015 Markus-Hermann Koch, mhk@markuskoch.eu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */

#include <iostream>
#include <sstream>
#include <string>
#include <QApplication>
#include "mhk_cmake_config.h"
#include "form_main.h"
#include "config.h"

using std::ostringstream;
using std::string;
using std::cout;
using std::endl;

using namespace display;

void gpl_msg()
{
	cout << endl << MHK_PROJECT_NAME << " V" << MHK_VERSION_MAJOR << "." << MHK_VERSION_MINOR << endl <<
	"Copyright (C) 2015 Markus-Hermann Koch, mhk@markuskoch.eu" << endl << endl <<
    "This program comes with ABSOLUTELY NO WARRANTY; This is free software, " << endl <<
    "and you are welcome to redistribute it under certain conditions;for details " << endl <<
    "see menu Help->Gnu Public License within the GUI." << endl << endl;
}

// Qt init function during the Khet project gratefully copied from:
// http://qt-project.org/doc/qt-4.8/mainwindows-application.html
int init_qt(int* argc, char** argv)
{
	// Parses the file generated by rcc from my xml resource file application.qrc
	// See CMakeLists.txt for details.
	Q_INIT_RESOURCE(application);
	QApplication app(*argc,argv);
	app.setOrganizationName(MHK_ORGANIZATION);
	ostringstream oss;
	oss << MHK_PROJECT_NAME " V" << MHK_VERSION_MAJOR << "." << MHK_VERSION_MINOR;
	string title = oss.str().c_str();
	app.setApplicationName(QString(title.c_str()));
	Form_main mainWin(0, DEFAULT_VERBOSITY);
	return app.exec();
}

int main(int argc, char** argv)
{
	gpl_msg();
	return init_qt(&argc, argv);
}
